# doc: https://docs.travis-ci.com/user/job-lifecycle/
language: cpp
sudo: required
dist: xenial
addons:
  apt:
    packages:
      - build-essential
      - python3
      - python3-dbus
      - python3-gi
      - libx11-dev
      - libgtk-3-dev
      - libgxps-dev
      - libcairomm-1.0-dev
      - libboost-tools-dev
      - libgtksourceview-3.0-dev
      - libpoppler-glib-dev
      - libgstreamer1.0-dev
      - gir1.2-gst-plugins-base-1.0

before_install:
- echo $LANG
- echo $LC_ALL
- env

script:
- ./build.sh

branches:
  only:
  - master

before_deploy:
  - git config --local user.name ${GIT_NAME:-TRAVIS-CI}
  - git config --local user.email ${GIT_EMAIL:-travis@example.com}
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true

env: # https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
  global:
      - LANG="en_US.UTF-8"
