dist: xenial
addons:
  apt:
    packages:
      - build-essential
      - python3
      - python3-dbus
      - python3-gi
      - libx11-dev
      - libgtk-3-dev
      - libgxps-dev
      - cairo-dock-dev
      - libboost-tools-dev
      - libgtksourceview-3.0-dev
      - libpoppler-glib-dev
      - libgstreamer1.0-dev
      - gir1.2-gst-plugins-base-1.0

before_install:
- echo $LANG
- echo $LC_ALL

script:
  ./build.sh

branches:
  only:
  - master

env:
  global:
      - LANG="en_US.UTF-8"
